-- ==========================================
-- Falken: Strategic Observability - State Descriptions
-- Stores human-readable round summaries generated by game logic
-- ==========================================

ALTER TABLE rounds ADD COLUMN IF NOT EXISTS state_description TEXT;

-- This helps the API recognize the new column immediately
NOTIFY pgrst, 'reload schema';
